In [38]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

### Load Dataset 

In [39]:
df_full_feature = pd.read_csv('../Dataset/Normalisasi/processed_dataset_10_norm.csv',sep=',')
df_chi_square = pd.read_csv('../Dataset/Normalisasi/processed_dataset_chi_square_norm.csv', sep=',')
df_feature_selection = pd.read_csv('../Dataset/Normalisasi/processed_dataset_5_norm.csv',sep=',')
df_slice = pd.read_csv('../Dataset/Normalisasi/processed_dataset_slice_norm.csv',sep=',')

### Feature Slicing 

In [40]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:9]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

src       dst  Protocol  pktrate  pktperflow       dur  dur_nsec  \
0  0.000000  0.941176       1.0  0.70579    0.705315  0.053163  0.716717   
1  0.000000  0.941176       1.0  0.70579    0.705107  0.148857  0.734735   
2  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   
3  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   
4  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   

   bytecount  pktcount  
0   0.328245  0.174242  
1   0.915781  0.486123  
2   0.654498  0.347427  
3   0.654498  0.347427  
4   0.654498  0.347427

In [41]:
# Dataset Chi Square 
chi_square_x = df_chi_square[df_chi_square.columns[:5]]
chi_square_y = df_chi_square['label']

chi_square_x.head(5)

dst       src  Protocol  pktcount  pktcount.1
0  0.941176  0.000000       1.0  0.174242    0.174242
1  0.941176  0.000000       1.0  0.486123    0.486123
2  0.941176  0.555556       1.0  0.347427    0.347427
3  0.941176  0.555556       1.0  0.347427    0.347427
4  0.941176  0.555556       1.0  0.347427    0.347427

In [42]:
# Dataset Feature Selection
feature_selection_x = df_feature_selection[df_feature_selection.columns[:5]]
feature_selection_y = df_feature_selection['label']

feature_selection_x.head(5)

pktrate  pktperflow  Protocol       src       dst
0  0.70579    0.705315       1.0  0.000000  0.941176
1  0.70579    0.705107       1.0  0.000000  0.941176
2  0.70579    0.705263       1.0  0.555556  0.941176
3  0.70579    0.705263       1.0  0.555556  0.941176
4  0.70579    0.705263       1.0  0.555556  0.941176

In [43]:
# Dataset Slice
slice_x = df_slice[df_slice.columns[:4]]
slice_y= df_slice['label']

slice_x.head(5)

dst       src  Protocol  bytecount
0  0.941176  0.000000       1.0   0.328245
1  0.941176  0.000000       1.0   0.915781
2  0.941176  0.555556       1.0   0.654498
3  0.941176  0.555556       1.0   0.654498
4  0.941176  0.555556       1.0   0.654498

### Feature Selection Model

Perlu untuk dilakukan diskretisasi karena nilai continous mengurangi performansi dari Naive Bayes

In [44]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(feature_selection_x,feature_selection_y,test_size=0.30,random_state=5)

In [45]:
nb_classifier = GaussianNB()
nb_classifier

GaussianNB()

In [46]:
nb_classifier.fit(x_train, y_train)

GaussianNB()

In [47]:
y_pred_train = nb_classifier.predict(x_train)
y_pred_test = nb_classifier.predict(x_test)

#### Training

In [48]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[44051     0]
 [28150     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     44051
           1       0.00      0.00      0.00     28150

    accuracy                           0.61     72201
   macro avg       0.31      0.50      0.38     72201
weighted avg       0.37      0.61      0.46     72201

Accuracy: 61.01162033766845


#### Testing

In [49]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18744     0]
 [12200     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.75     18744
           1       0.00      0.00      0.00     12200

    accuracy                           0.61     30944
   macro avg       0.30      0.50      0.38     30944
weighted avg       0.37      0.61      0.46     30944

Accuracy: 60.57394002068253


### Slice Model

In [50]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(slice_x,slice_y,test_size=0.20,random_state=4)

In [51]:
nb_classifier_slice = GaussianNB()
nb_classifier_slice

GaussianNB()

In [52]:
nb_classifier_slice.fit(x_train, y_train)

GaussianNB()

In [53]:
y_pred_train = nb_classifier_slice.predict(x_train)
y_pred_test = nb_classifier_slice.predict(x_test)

#### Training

In [54]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[50296     0]
 [32220     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     50296
           1       0.00      0.00      0.00     32220

    accuracy                           0.61     82516
   macro avg       0.30      0.50      0.38     82516
weighted avg       0.37      0.61      0.46     82516

Accuracy: 60.95302729167676


#### Testing

In [55]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[12499     0]
 [ 8130     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.75     12499
           1       0.00      0.00      0.00      8130

    accuracy                           0.61     20629
   macro avg       0.30      0.50      0.38     20629
weighted avg       0.37      0.61      0.46     20629

Accuracy: 60.589461437781765


### Chi Model

In [57]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(chi_square_x,chi_square_y,test_size=0.30,random_state=9)

In [58]:
nb_classifier_chi = GaussianNB()
nb_classifier_chi

GaussianNB()

In [59]:
nb_classifier_chi.fit(x_train, y_train)

GaussianNB()

In [60]:
y_pred_train = nb_classifier_chi.predict(x_train)
y_pred_test = nb_classifier_chi.predict(x_test)

#### Training

In [61]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[43895     0]
 [28306     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     43895
           1       0.00      0.00      0.00     28306

    accuracy                           0.61     72201
   macro avg       0.30      0.50      0.38     72201
weighted avg       0.37      0.61      0.46     72201

Accuracy: 60.7955568482431


#### Testing 

In [63]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18900     0]
 [12044     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     18900
           1       0.00      0.00      0.00     12044

    accuracy                           0.61     30944
   macro avg       0.31      0.50      0.38     30944
weighted avg       0.37      0.61      0.46     30944

Accuracy: 61.07807652533609


### Full Model

In [64]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=9)

In [65]:
nb_classifier_full = GaussianNB()
nb_classifier_full

GaussianNB()

In [66]:
nb_classifier_full.fit(x_train, y_train)

GaussianNB()

In [67]:
y_pred_train = nb_classifier_full.predict(x_train)
y_pred_test = nb_classifier_full.predict(x_test)

#### Training

In [68]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[43895     0]
 [28306     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     43895
           1       0.00      0.00      0.00     28306

    accuracy                           0.61     72201
   macro avg       0.30      0.50      0.38     72201
weighted avg       0.37      0.61      0.46     72201

Accuracy: 60.7955568482431


#### Testing

In [69]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18900     0]
 [12044     0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     18900
           1       0.00      0.00      0.00     12044

    accuracy                           0.61     30944
   macro avg       0.31      0.50      0.38     30944
weighted avg       0.37      0.61      0.46     30944

Accuracy: 61.07807652533609


Perlu pemilihan fitur kembali karena pointnya masih kurang baik akurasinya, dan belum tahu ketika nanti di kombinasikan dengan LSTM, selain itu perlu mengetahui lagi mengenai Gaussian NB dll